version: "3"

services: 
  - app:
      build:
        context: .
      ports: 
        - "1313:1313"
      volumes: 
        - ./app:/app
      command: >
        sh -c "python manage.py runserver:0.0.0.0:1313"
        