# Generated by Django 3.0.8 on 2020-07-28 15:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_myuser_date_joined'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='myuser',
            name='date_joined',
        ),
    ]
